# Generated by Django 2.2.3 on 2019-07-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField(auto_now_add=True, help_text='Date on which event was created.')),
                ('event_name', models.CharField(help_text='Enter the name of the event.', max_length=100)),
                ('event_date', models.DateField(help_text='Date of the event.')),
                ('batch_size', models.PositiveIntegerField(help_text='Enter batch size.')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, help_text='Date on which booking was registered.')),
                ('booked_by', models.CharField(help_text='Name of the person who made the booking.', max_length=100)),
                ('participants_count', models.PositiveIntegerField(help_text='Number of participants')),
                ('contact_number', models.PositiveIntegerField(blank=True, help_text='Enter mobile number.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Event')),
            ],
        ),
    ]
