# Generated by Django 2.2.3 on 2019-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190716_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('t', 'Trek'), ('c', 'Camping')], default='t', help_text='Type of event(Trek/Camping)', max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants_count',
            field=models.PositiveIntegerField(help_text='Number of participants.'),
        ),
    ]
