# Generated by Django 2.2.3 on 2019-07-21 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190718_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_of_payment',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of payment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='mode_of_payment',
            field=models.CharField(default='Cash', help_text='Mode of payment.', max_length=100),
            preserve_default=False,
        ),
    ]
